const planes = [
    {
      id: 11,
      index: 0,
      type: 1,
      name: "P-51 Mustang",
      img_url: 'https://www.plane-encyclopedia.com/wp-content/uploads/2016/08/Swamp-Fox-p-51d.png',
      role: "Fighter Plane",
      country: "United States" ,
      side: "Allies",
      main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
        speed: "437 mph",
        range:"2,300 miles",
      description: "The M4 Sherman (named after the famous American Civil War general William T. Sherman) is one of the few really iconic fighting vehicles of the Allies during World War Two, and one of the most famous tanks in history. But while this historic status was gained partly thanks to its intrinsic qualities, but also due to the sheer numbers in which they were provided, only surpassed by the Soviet Union’s T-34, with a staggering 50,000 total delivered. It remains by far the most widely used tank on the Allied side during the war. It was derived into countless derivatives and had a very long postwar career which lasted well into the Cold War. It has been largely compared to the T-34, and had the occasion to confront some during the Korean War.",
    },
    {
      id: 12,
      index: 1,
      type: 1,
      name: "Vought F4U Corsair",
      img_url: 'https://www.plane-encyclopedia.com/wp-content/uploads/2016/09/F4U-4-VMF-124-13-Kenneth-A.-Walsh-Okinawa-06-45_03.png',
      role: "Fighter Plane",
      country: "United States" ,
      side: "Allies",
      main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
        speed: "437 mph",
        range:"2,300 miles",
      description: "The Cruiser Tank Mk IV (A13 Mk II) was a British cruiser tank of the Second World War. It followed directly on from the Tank, Cruiser, Mk III (A13 Mk I). The first Mk IVs were Mk IIIs with extra armour fitted to the turret. Later Mk IVAs were built with the complete extra armour. The tank was used in France in 1940 and in the early part of the war in North Africa, before being withdrawn from service. In total, 955 of these tanks were built.",
    },
    {
      id: 13,
      index: 2,
      type: 1,
      name: "Focke Wulf Fw 187",
      img_url: 'https://www.plane-encyclopedia.com/wp-content/uploads/2018/12/Focke-Wulf-Fw-187-A-0-Side-View.png',
      role: "Bomber Plane",
      country: "German" ,
      side: "Axis",
      main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
        speed: "437 mph",
        range:"2,300 miles",
      description: "When comparing the small number of Panzerkampfwagen VI Ausf.E (Sd Kfz 181) Tiger Tanks produced (only 1346), to the more than 120,000 T-34s and Shermans combined, one can appreciate the psychological impact of this model, at least from the Allied tank crew perspective. In its concept laid the very core of the German conception of a heavy tank. Something which targeted absolute excellence in design, combining lethality with the best possible protection, only given to elite crews, all this regardless of the cost. Excellent engineering and training versus numbers underlined all this philosophy and was reflected, later, in small tactical unit operations.",
    },
    {
      id: 14,
      index: 3,
      type: 1,
      name: "Messerschmitt Me 209",
      img_url: 'https://www.plane-encyclopedia.com/wp-content/uploads/2017/08/Me209v4_03.png',
      role: "Fighter Plane",
      country: "German" ,
      side: "Axis",
      main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
      speed: "437 mph",
      range:"2,300 miles",
      description: "Planned since the beginning of the thirties, with the rejection of the Versailles treaty, the Panzer III was a medium tank project, destined to comprise the bulk of the German armored forces. However, by 1933, German industry was still unable to produce such a tank, and the Panzer I and II were intended to improve industrial skills and methods, as well as to train crews for the future medium tanks to come. The Panzer III’s godfather was Heinz Guderian, a prolific armored warfare writer and theoretician, who envisioned an ideal design for the task of both dealing with other tanks and providing infantry support.",
    },
    {
        id: 15,
        index: 4,
        type: 1,
        name: "Messerschmitt Bf 109",
        img_url: 'https://www.plane-encyclopedia.com/wp-content/uploads/2016/10/Bf109_Wespe.png',
        role: "Fighter Plane",
        country: "German" ,
        side: "Axis",
        main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
        speed: "437 mph",
        range:"2,300 miles",
        description: "The Panzer IV saw service in all combat theaters involving Germany and was the only German tank to remain in continuous production throughout the war. It received various upgrades and design modifications, intended to counter new threats, extending its service life. Generally, these involved increasing the Panzer IV's armor protection or upgrading its weapons, although during the last months of the war, with Germany's pressing need for rapid replacement of losses, design changes also included simplifications to speed up the manufacturing process",
      },
    //   {
    //     id: 6,
    //     index: 5,
    //     name: "Panzer V Jap Zero",
    //     img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Medium_Tanks/Panzer-V_Panther/Panther_Ausf-D-1_Turm-IV.png',
    //     role: "Fighter Plane",
    //     country: "Japan" ,
    //     side: "Axis",
    //     main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
    //     speed: "437 mph",
    //     range:"2,300 miles",
    //     description: "Panther tanks first saw action on the Eastern fronts. They were also used in Italy, France, Belgium and Holland. They took part in the Ardennes offensive, the battle of the Bulge plus the defence of Germany. It had better cross-country mobility than the Tiger tank and had the same if not more hitting power, with its 7.5 cm Kw.K 42 L/70 long barrelled high velocity anti-tank gun. Around 6,000 were produced.",
    //   },
    //   {
    //     id: 7,
    //     index: 6,
    //     name: "StuG IV",
    //     img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Panzerjagers/STUG-IV/Sturmgeschutz-IV_Germany45.png',
    //     role: "Assault Gun",
    //     country: "German" ,
    //     side: "Axis",
    //     main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
    //     speed: "437 mph",
    //     range:"2,300 miles",
    //     description: "The story behind the StuG IV is somewhat chaotic. It was born inside Krupp’s factory walls in the shadow of the successful StuG III. The company was, at the time, responsible for producing the Panzer IV. By 1943, it was producing the Ausf.G/H, while Alkett’s Sturmgeschütz III Ausf.G (the best version) was barely entering service on the Eastern Front. Krupp prepared the drawing number W1468 in February 1943, combining a remodeled superstructure from the StuG III Ausf.F with the ninth chassis version of the Panzer IV, but it was dropped as being too heavy. In August 1943, Hitler was given reports on the performance of the StuG III at the battle of Kursk, which pointed out relatively superior performances of the StuG III Ausf.G compared to the Panzer IV. He ordered Krupp to switch production to a dedicated tank-hunter, the Panzerjäger IV, that would be equipped with the same 7.5 cm L/70 used by the Panther",
    //   },
    //   {
    //     id: 8,
    //     index: 7,
    //     name: "Jagdpanzer IV",
    //     img_url: 'http://www.tanks-encyclopedia.com/ww2/nazi_germany/Panzerjagers/Jagdpanzer-IV/Jagdpanzer-IV-70(A)-Ardennes1944.png',
    //     role: "Tank Destroyer",
    //     country: "German" ,
    //     side: "Axis",
    //     main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
    //     speed: "437 mph",
    //     range:"2,300 miles",
    //     description: "The Jagdpanzer IV, Sd.Kfz. 162, was a German tank destroyer based on the Panzer IV chassis and built in three main variants. As one of the casemate-style turretless Jagdpanzer (tank destroyer, literally hunting tank) designs, it was developed against the wishes of Heinz Guderian, the inspector general of the Panzertruppen, as a replacement for the Sturmgeschütz III (StuG III). Guderian objected against the needless, in his eyes, diversion of resources from Panzer IV tank production, as the Sturmgeschütz III was still more than adequate for its role.",
    //   },
    //   {
    //     id: 9,
    //     index: 8,
    //     name: "T26E4 Super Pershing",
    //     img_url: 'http://www.tanks-encyclopedia.com/ww2/US/Heavy/M26_Pershing/T26A4_Super-Pershing.png',
    //     role: "Heavy/Medium Tank",
    //     country: "United States" ,
    //     side: "Allies",
    //     main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
    //     speed: "437 mph",
    //     range:"2,300 miles",
    //     description: "The M26 Pershing was deployed rather late onto the battlefields of WWII, with the first 20 landing in the Belgian port of Antwerp in January 1945. These tanks would be the only Pershings to see combat in World War Two, spread between the 3rd and 9th Armored Divisions, part of the First Army. The tanks drew their first blood in late February 1945 in the Roer river sector (not be confused with the Ruhr), with a famous duel taking place in March at Köln (Cologne).",
    //   },
    //   {
    //     id: 10,
    //     index: 9,
    //     name: "T-34/76",
    //     img_url: 'http://www.tanks-encyclopedia.com/ww2/soviet/Medium_Tanks/T34-76/t34-76_sovietcamo.png',
    //     role: "Medium Tank",
    //     country: "Soviet Union" ,
    //     side: "Allies",
    //     main: "6 X .50 caliber (12.7mm) AN/M2 Browning Machine Guns, 2 hardpoints that could allow 453 lb (907 kg) of payload. 2 x 100 lb (45 kg) bombs; 2 x 250 lb (113 kg) or 2 x 500 lb (226 kg) bombs. 6 or 10 x 5.0 in (127mm) T64 H.V.A.R rockets"  ,
    //     speed: "437 mph",
    //     range:"2,300 miles",
    //     description: "The T-34 was and remains a legend. It is not only the most produced tank of the WWII-era, with 84,000 built (compared to the 48,966 Shermans of all versions) but also one of the longest-serving tanks ever built. Many are still stored in depots in Asia and Africa, and some served actively during the 90’s (such as during the 1991-99 Yugoslavian war). They formed the backbone of countless armored forces around the globe from the fifties to the eighties. The basic design was drawn for the first time in 1938 with the A-32, in turn partially derived from the BT-7M, a late evolution of the US-born Christie tank.",
    //   },
  ]
  
  export default planes